---
abstract: 'Yet another lazy, minimal way of using Getopt::Long'
author:
  - 'Ruey-Cheng Chen <rueycheng@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Getopt-Lazy
no_index:
  directory:
    - t
    - inc
requires:
  File::Basename: '1'
  Test::More: '0'
  Text::Wrap: '1'
  version: '0'
version: v0.0.7
